CREATE TABLE DON_MENU_INFO (
 MENU_ID VARCHAR(32) DEFAULT NULL COMMENT '菜单ID',
 MENU_PID VARCHAR(32) DEFAULT NULL COMMENT '菜单父ID',
 MENU_NAME VARCHAR(32) DEFAULT NULL COMMENT '菜单名',
 MENU_URL VARCHAR(256) DEFAULT NULL COMMENT '菜单URL',
 MENU_TYPE VARCHAR(2) DEFAULT NULL COMMENT '菜单类型（0目录 1菜单 2按钮）',
 MENU_ICON VARCHAR(34) DEFAULT NULL COMMENT '菜单图标',
 MENU_ORDER VARCHAR(4) DEFAULT NULL COMMENT '菜单顺序',
 MENU_STATUS VARCHAR(2) DEFAULT NULL COMMENT '菜单状态（0正常 1停用）',
 REMARK VARCHAR(100) DEFAULT NULL COMMENT '备注',
 CREATE_BY VARCHAR(24) DEFAULT NULL COMMENT '创建人',
 CREATE_DATE DATE DEFAULT NULL COMMENT '创建时间',
 UPDATE_BY VARCHAR(24) DEFAULT NULL COMMENT '修改人',
 UPDATE_DATE DATE DEFAULT NULL COMMENT '修改时间',
 DON_MENU_INFO_ID VARCHAR(36) NOT NULL DEFAULT 'sys_guid()' COMMENT '主键',
 PRIMARY KEY (DON_MENU_INFO_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='菜单信息表';